title: Moses Okumu
logo: FB_IMG_1741260394939.jpg
theme: jekyll-theme-minimal
description: |
  Passionate about Data Analytics and Visualization using Power BI, R, and Python.

  ![R](https://img.shields.io/badge/R-276DC3?style=for-the-badge&logo=r&logoColor=white)
  ![Power BI](https://img.shields.io/badge/Power%20BI-F2C811?style=for-the-badge&logo=powerbi&logoColor=black)
  ![Python](https://img.shields.io/badge/Python-3776AB?style=for-the-badge&logo=python&logoColor=white)


