title: Moses Okumu
logo: FB_IMG_1741260394939.jpg
[view on github](https://github.com/Mose742/my_first_repo_2025/blob/main/gapminder_copy.qmd)
theme: jekyll-theme-minimal
github:
  is_project_page: false


