title: Moses Okumu
logo: FB_IMG_1741260394939.jpg
theme: jekyll-theme-minimal
description: |
  Passionate about Data Analytics and Visualization using Power BI, R, and Python.
github:
  is_project_page: false

